GET http://localhost:4000/chart

###
POST http://localhost:4000/chart
Content-Type: application/json

{
    "title": "金融大数据",
    "user": "1234"
}

###

GET http://localhost:4000/demo/percent

###

GET http://localhost:4000/demo/pv
